apiVersion: ENC[AES256_GCM,data:9DA=,iv:Rbo9OQe9TlUmVHj/9pmpOQBrMyBwEfKX9nj19/F1Kac=,tag:X1/F+Krs2CzpS2dwUV+t9g==,type:str]
kind: ENC[AES256_GCM,data:ZpI5kehh,iv:7oQjidaA4THujORpw1UYjcmlhgoIHFY1SjUCEzvzP9k=,tag:qtdsfTeLajOs32q6ge0dMw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:oiVH3FCoMRslCEfq,iv:74MMBtffOf4MGkx0tUSG5JG9erBQMYHZ1AB4jB0CPdw=,tag:j67eHRZpXPbYPfKcWNxy0A==,type:str]
    namespace: ENC[AES256_GCM,data:WnTYRCA=,iv:QuwOp44EqjkesQH9bCBqEZ9SWMlE0hArG+F1pDSSJCQ=,tag:aKhNmd0aghoXikKo/Rsg4g==,type:str]
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:gTfpOQBUTYhTlenfiql7ia1tZFOpOSsa3r/m9cmm6SUqBYqhJN0FPUfUKr8=,iv:UWEvjAcm/dRu5mLGsxdH0jnhxgprvWsrzWGb+p/MfFY=,tag:PNQoQF0ZclzkJgfMSZcwsw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSDlNM2ZLV1FUTE9iNHI4
            aFRhSDVTNHBOcG1heVNiQVNuOXdNT3JmeFJNCmRxVEtUM3NCYWxFbWxLczhlYkpy
            aHVXS05NcGMzVjlaYmhDZWdxbHg1Y3cKLS0tIGhYdkxJWGVhOUE0ck5wTk56c0dN
            d1VubEo4TkVTMk56OEhCWDdiSzdPWWMKD+hStU3IVO1e6hMq6b/TKpMzVgxfF/T9
            qB3Jok0WM133JeVPJB8/pp5DEJB1Xnb7aBM7j85A4Xxgd34ubEqCZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ht8d6zlqkpex3kfvr2dneldyjj7xnwh7nmjx3mmwclt7rl7upynsarwwm5
    lastmodified: "2026-08-04T11:16:39Z"
    mac: ENC[AES256_GCM,data:N44u1hkXEbrl80TY3NYUGnJYiY2+wmIMjE9ldAqufanyB1FhCE6p+GYImG1b8cro/jisBaVtsvFgj8yEzUcuqVszlHr8+KJyWSo3obTNCWzW/0jIC4X524uL0J39xHlIiFfaM9OZmwWb1QrgvYY8gS5HedQPp/48e5Nc0G48CXE=,iv:W6x496ZWKdKEDaaSFt0zZnzWFrZGVhSHAGgCNei9kk0=,tag:fDKXKt5XzQLmAyTW0S2qKQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
