k3s_version: "v1.30.2+k3s1"

# Networking
# We bind the API to 0.0.0.0 so it listens on all interfaces,
# but we add the IPs to the certificate so secure connection works.
k3s_server_args: >-
  --tls-san {{ ansible_host }}
  --tls-san 100.84.231.21
  --write-kubeconfig-mode 644
  --disable-cloud-controller
  --disable traefik
# --kubelet-arg="protect-kernel-defaults=true"
k3s_admin_user: "arjun"
