apiVersion: ENC[AES256_GCM,data:3oU=,iv:1Yx2LewZM35nfkgebC8SlYTlsARXARq9fSNMBwChN7w=,tag:k20bvoYP09qmcAXiIrO+cg==,type:str]
kind: ENC[AES256_GCM,data:QETJFajM,iv:Ak8uMA/nhXx0/HQkAul+2RcjIIHj/Ny7ey9USnf3VKk=,tag:2nUlDnJ3S4jfqm0+TpUJJw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:O2FV7kihm7QMyHaQw1qGmW+5/8U=,iv:2vr7q5ye+93L4lUeCa2IpnLgcYZlcehpQC8l0f72Rnw=,tag:woxkyNRtiyK9H5/ujVaBxg==,type:str]
    namespace: ENC[AES256_GCM,data:UZoXOyvPT7H1+Udj,iv:2hGYcKQW5gXnI6441UKX1KO71nMLVB2MWq/mP52JjEQ=,tag:PjIlOydp+vqdFdHtEtuK0A==,type:str]
type: ENC[AES256_GCM,data:OjXWKr0e,iv:q5xvw3Ve54WT9ocIFXT8WWs9gE388osjIXkUlJGov2Q=,tag:qXpzX1KAXb1RvFSdX3QokQ==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:tbKWJbifuy4Krph+ZN35Rff4GcZbSdMFC6tdVYaCRtZ2DFeTYwMATA==,iv:WrnYEQ4jqAbLlWwQqmEnvWcUKEB3ufJ0IWN9YWf7TC0=,tag:9Gl6gKV+K5sGjw1uON1vOQ==,type:str]
sops:
    age:
        - recipient: age1ht8d6zlqkpex3kfvr2dneldyjj7xnwh7nmjx3mmwclt7rl7upynsarwwm5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3RS9ZWnBDSHJGTSszdGtx
            Y1UxY0trcHBUTE1DZkM4NUZJckhsUGtLWENFClU1bEQ0dXUyM1UyTlFibnI5Y1VX
            TGdXUE4rZSsrYjJJL1dmRXBDZG9aVVUKLS0tIDhuUlJCdk9JZjczbDdiZEhrdS9W
            MGZLY05hbjJjTWhvR05JRERxVG9VY1kKVarRolgm9lIKQLoGOggt9lheWZFFRlgp
            MSQwN2OvjHYZwuji0ZrYkfrgai9gZg093utkbIKdKT5gUZ9JBwb9rA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-07T17:23:38Z"
    mac: ENC[AES256_GCM,data:oQcgtsA+MWy/WHhf73IgHmEJ8RmVU0TKvse8T6v+NgtgXvXtxeM+tOVqJChdM532vHjT593l+xT4FVc/Xzia/a5T+RVqn1BH2bJbCa/BsM0dFPQnXbw+IIVypzd5Zt4umAaDimdUviahxOgXwSBe+YSgnoj5OQiHH7HkHMso16c=,iv:KqfWLrb8KkUeGXSoDhiO9jtk2XMUGAu9gYpOxXTG3h4=,tag:6tc52ZHUk8RaL5p2/0GtTQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
