apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: axiom
resources:
- namespace.yaml
- rbac.yaml
- fluent-bit-config.yaml
- fluent-bit-daemonset.yaml

generators:
  - secret-generator.yaml
