apiVersion: ENC[AES256_GCM,data:vlI=,iv:93QSjJ6+L4MhHoTwlzdEiXwXxaeeOs1Z1flmkiO9VzI=,tag:2z6AlRWKCAjGuj2v2cIHCQ==,type:str]
kind: ENC[AES256_GCM,data:0g3QcHik,iv:UJrvF0V5uxD6HIBK7CcjnfVee17fvsKGqYIkmOvA2kY=,tag:mCpDFT4B9+zyFseAXbTE2A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:mM2vUfKSaKieLJ1+mvyUDwU=,iv:7ZzVULWEXFCWqZzaqFb3Jepi7Bp2AHJZimw1HBksgEQ=,tag:5ZFqcgokmc3QI8athA/ayQ==,type:str]
    namespace: ENC[AES256_GCM,data:1B4d8MA=,iv:sLRhrk1evKRbGevIg+hPF92/IzOzOSXwVbuqIkTWcw=,tag:5rAgLHa/xHIp0beZA5m+uA==,type:str]
type: ENC[AES256_GCM,data:yUHDT2Tx,iv:fr4jkOf1XRUchDXzyp9PBQvu2oM8rTGQfd9QoU2uqdc=,tag:pVrlGZdKLl6zer2T5HRBAA==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:BsD6IhbTxTA+3CnNlvkQ5kdW8dpMFJdTyB/SZn8yjcM00bX0P4l96z8=,iv:WocmWc6m7TgBNmIdRuTFdBVMwZYJvVBGq93GDm7+QNE=,tag:T65Bw7eZk6nPw2k6CvL1YQ==,type:str]
    org-id: ENC[AES256_GCM,data:ru38JEk7x0Sr,iv:S6g1Eehiwve0D8vQsAkYyzCE+8MT2J4oAnvsb8vbWAY=,tag:AW3juDND5yZewMcg7VAPSw==,type:str]
    dataset: ENC[AES256_GCM,data:jnKHMpPPzXKuBorH,iv:TsHNlOdMnhR6EduNZxvTgcKOaWKyMp0K5xMG/Mi2q+c=,tag:br/BAvqZFW4yc0fcbSFxMw==,type:str]
sops:
    age:
        - recipient: age1ht8d6zlqkpex3kfvr2dneldyjj7xnwh7nmjx3mmwclt7rl7upynsarwwm5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVa2YwTmRMalVkNGdXa3Z1
            WjVHVkdXQUpMY2lMRXI3YlA4QmxEUlczQkVnCjFFMEpwa2V4L2Z2VXFibWVoWVZn
            Tk5ZVDZaZmtnSlcrNS9MV1Nsc0Y5Q00KLS0tIHVteUVTUkZRVExOZmFqUHEzYXVj
            dTdzS2s2ZWtjNzVXZ2RtTDZibGFUK3cKVBuoAEaFv/6V7yKOqf4xhR+OWkNSbxy/
            Afb8IWJY2RZ8Ccoj5wUmlAlBVLoz9ds9pxMHXX4ym9pXqYOudJ3nDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T12:03:27Z"
    mac: ENC[AES256_GCM,data:MVHNcAJr3+SfzGAQ1LmctbSNWUog4J1FuUvmkXJ7gv6Ln3ODxBnGLL/zfYzqpx4IXUnYKkiVGnYHfQ1bYDR98i4Lnyl9vDCVfiBaExovMr0JUob4pqMoKdDewRM3+ZV9VSFCIux8FvULN/Jipw25S2Uvv/RzWYcw4d/9kJIDZlE=,iv:E/D/CY67dYVVwTkZyX4QuSbSIbgAHV1Gs0xyvs61+Fg=,tag:gwBbfOvlfhw3OXCMW39nng==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
