apiVersion: v1
kind: Secret
metadata:
    name: axiom-credentials
    namespace: axiom
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:sJoGRWfhXvgmyUpLYrKwjsSFLlCVQ9y6+vuCIQ5cqiUjpogIBFyGJB0=,iv:ucHCah+rYVVdm7h0IcFAUDL0xTtziiPsXkuGul3g5xA=,tag:gwi3Nux3lByQK+xCLbAEWw==,type:str]
    org-id: ENC[AES256_GCM,data:FZjxXsOibKtS,iv:2TkJFBMaipX76etpbZ/aCDxyynugXKaAXxMZiPep1+M=,tag:ReMwCzlCUR64aNarICYU/w==,type:str]
    dataset: ENC[AES256_GCM,data:8LhHxXj9lZBaUQhe,iv:99c+bIPTfI7wmSvyLhWvFGDQ0sJSj8zeJlUI2id/uFM=,tag:pT1EPcVPst+HZF1UtGf1PA==,type:str]
sops:
    age:
        - recipient: age1ht8d6zlqkpex3kfvr2dneldyjj7xnwh7nmjx3mmwclt7rl7upynsarwwm5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Y1BJZ1pYakVFcWZGZDUv
            bzB4M0pZNUNSbTBWcHl6WCs5K3FZTUhMckdrCkdRSlE5THlDT1B1dG5VM0ZOYWhq
            UzBUb0cyZC81dVNkVHY0VkRSZk5uR00KLS0tIGpwWGNTYkR0NFdOK0lkOVBsdXdk
            T3hyMmZoQnhzRU4rblJ3QUh5WE5kbDQKfl6b0Kb5Wf7WisW1b1Qk3/LQWtZ29rk8
            kugIIAPXyP1jddtRPQZrfdxqSpb5mY+okXzHRyO8GcC7xlaJxquCVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T16:36:26Z"
    mac: ENC[AES256_GCM,data:vSq1nGBVfdZV3tJ0y4beAx/wgelmdupG7LTykBbTwaoophiDvp5dWCc3fHybV1ygd8KEN4UHkUfWpKbGSwIo7U3NGeBskh9FPhluI9ouzOI1hL7EjihibTtblXD/wV67/rnmwsDZW2MyUW3SF9FYx16uIUlkQf428H3rKOzf590=,iv:IkwGOBv0smkFnqxWr1l+n7rpdop5m9yEYYGdVhsq1yQ=,tag:IGIQnQwraqAjTShM/pIgmA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
