apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nihalxkumar-dev
  namespace: landing
spec:
  secretName: nihalxkumar-dev-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - nihalxkumar.dev
    - www.nihalxkumar.dev