apiVersion: ENC[AES256_GCM,data:z2A=,iv:g8W9RV+RgYuwMW7ITNBdDxYvflcBkZwocNMByOttz0w=,tag:3Y3EzWDaa51Xo29o9qMxpg==,type:str]
kind: ENC[AES256_GCM,data:klABD7Sm,iv:hajgJSSzsW2+O4vofEMA0mBuAvEk7d+1VQoc8P3DRcQ=,tag:C6obWLqeQA5/6BL5nB7RBA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:rQ/YqmI+AwcNdrbn/lg=,iv:ckApfOcDpj9xCAHYqE7vrgCwBKT2ixUE7hPqNkPCXaU=,tag:pQeI238HspkMQl/M1rLrjA==,type:str]
    namespace: ENC[AES256_GCM,data:KaOcs6EVvKQU,iv:UofG/XP4Yn/q8SljsUii5PETXIejwVV+r2CDBGA1EBo=,tag:+2/iqiUklb6O1ve3KsEprg==,type:str]
stringData:
    #ENC[AES256_GCM,data:+kEDDP4hsE8qO+S+UymOpLeav1pZQUDeOFVMtMzDoa+AibXEnJUpauK6zqLb29OWevp1cfplWRXqEwuyE44RXQ==,iv:ycbtGHkncwnh8iNCn/9bldAmMSXq7yOniI6xQlz6fJ4=,tag:84byl0G0X+9cwA9VuMuf+A==,type:comment]
    #ENC[AES256_GCM,data:1+a2m4m+SahV9KEoyxJxZFYgqlwXzzfuW3iO64zxEkI/Tw1mh40C1pRCJvID6x47m+xcMpVC,iv:m2uRtKPp0UQIs8qZ9O8s9jIT30KBck7AVKkI9Hxrmsg=,tag:gSiMJM8BAihU8+YU4bAwtA==,type:comment]
    client_id: ENC[AES256_GCM,data:CaKnwxXIg5shCehw8tTUN7w=,iv:7SeetvMdtuE79kf6DUWYslCO2TL78gakUhyTVgXSx4w=,tag:Oio9ixkXoP1eYCVtITDm/w==,type:str]
    client_secret: ENC[AES256_GCM,data:sfnQEXjI7+E9gi00FIwgcWs6FrAHBt28jb40AELTspPS6lEltI+t2pGHptmeGaCyNDx4cX4o/iABR5SACV4Obg==,iv:efsi4SShBgY56U6e4yrWLOg5jxg0zLTyFoMN5N3eL4M=,tag:NmlF6s9v3AUvvciRbOUXlg==,type:str]
sops:
    age:
        - recipient: age1ht8d6zlqkpex3kfvr2dneldyjj7xnwh7nmjx3mmwclt7rl7upynsarwwm5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0QkV1bzZ4QW9xOHdxbElm
            a0VYeDVXZm1OeXFsbXJrRkNRZWhsS0NyVDJBCmw0Z0RHN2hRSENlSDZIbFN0Sko0
            NThqNTc2dStoSVVQYlNYQUx6bTlLckkKLS0tIHRMS1kxVVZrckRQbXBZdWtNSEZC
            MytNQzNVakM4U1RUNVE2SEtYZ0lJckEKyEY7WnLyDblSUInNYyHYWiXhcx8lB2BJ
            2hgUP1Tt0ZC2H0fnoxcgh6/dUiKhUAqBxMUt1jEJzbidwRRWdCv1hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-09T15:36:53Z"
    mac: ENC[AES256_GCM,data:u7fAkkeLXBnXX9I1vCRdB+SpiUvoOnevgAHIldxAnDVnYYx+mRUqur4Op/XX3bbxIKx1VVO5bkwKsa4Ub7gT4TP/g9Ctok6lhJKB8TG7PpXV5x8V4fb9nZgbR5+ubwg2O3I/iYGeFBUun33Szxa2MpY9iBBsdg+M4onLKPgq6z0=,iv:fqRzgGl0BxBucv86bJmc4+VcvYfSQ6J3marOOF4flD8=,tag:GzdLHtl+NOQ8Ktf5MjuOAA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
