apiVersion: v1
kind: ConfigMap
metadata:
  name: deepwiki-config
data:
  NODE_ENV: "production"
  SERVER_BASE_URL: "https://deepwiki.nihalxkumar.dev"
  LOG_LEVEL: "INFO"
  LOG_FILE_PATH: "api/logs/application.log"
  DEEPWIKI_EMBEDDER_TYPE: "google"
