apiVersion: ENC[AES256_GCM,data:UO8=,iv:Jc7oaiq9mFTOEMHvXoQOQN5GHJaEGfimf1hQ48fz2Tw=,tag:/UITBxCkJRrbaEKzEupjeA==,type:str]
kind: ENC[AES256_GCM,data:w98QvhLm,iv:cmJDxIm2l4poIQ/KLwiEtyZXuKTNzfKKlqIqRz+PqZU=,tag:adV+AEDhIh4zWTLkyyQloQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:RhLzBSEe4gkimPJs1UEq,iv:wK29NLRC2Hjfr/FOjw5BCb0Q1nrrQdF0ldNzpdDEA5o=,tag:EN5dvUTVWBF1uysAioJQ3A==,type:str]
stringData:
    GOOGLE_API_KEY: ENC[AES256_GCM,data:mvj735KEX0DW9rtPotlEuttlrLQu2LVL2fLlwq2QeraIZ4wncUyR,iv:vA7g/B+aTsN3wca57W9FR2hN0lRS5BNBRSrqb9BtcSU=,tag:O6P3eYERI/HMY1jADR7e2A==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:XIYEIf+lgd89,iv:Wh1K1SYKcF6IfOSxMr99VvS6YkhYZLyxdG2T+fYeeEs=,tag:P4187sSXqZSbpNk4khg53w==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:HMs3+V6S6EOG,iv:vMKgK5dMItrlQxrKFy0Cd0kuH0Bce+MfnGcMkRWT58A=,tag:E3hike3fa+ISc7AgfwYKGg==,type:str]
sops:
    age:
        - recipient: age1ht8d6zlqkpex3kfvr2dneldyjj7xnwh7nmjx3mmwclt7rl7upynsarwwm5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTUmxBdWV2M2pEOWUrYTBF
            UWR3NTdHQVdTc3h4cWY2VFVzZllwNWp6cjBzClZZMHZPbmNjdVhIanFDL2x3N0M5
            TkRJYkorZXVuek40MmRjZHRDUVlwU2sKLS0tIDIrUks2VzNuRFVhT3diS3lQL0o2
            ZUFSQ3l5eW5FOVp4YjZnOHA0Y2hHancKAiYknE+MV0//gm0fdJRFRr7RbmAK/em3
            CeDLlfcX+Yu5oHfRKsIRdKyZg7SZX3pd1gjweH9lUFfJ58PJmouPDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T15:57:10Z"
    mac: ENC[AES256_GCM,data:Zng79Pl8noHGf6DMuTAyFYABVsYHbfZuxmylGZr4c6+ybOwD2Fy8ixB6hYtwTWilFWVix2NNF0hr3+FXvFB1y0k5n4VQE6QD8qKOSZTuhPjqAHhUsoBe/HmLf4STqhByx/AJqspIXQ/H7ogPMg2cTPBM3wW1O442QlleCMuxkDc=,iv:ILDOJL+tDq2uJzzahIlTqK8QyiVHdmOAYvfXlRvC0Yo=,tag:ftmxpISlX8xBFP74QOAZtQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
