apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: homelab
  source:
    repoURL: https://helm.traefik.io/traefik
    chart: traefik
    targetRevision: "28.0.0"
    helm:
      releaseName: traefik
      values: |
        # Install Traefik CRDs so IngressRoute, etc. are available
        installCRDs: true
        
        deployment:
          replicas: 1
        
        metrics:
          prometheus:
            enabled: true
        
        logs:
          general:
            level: INFO
          access:
            enabled: true
        
        ports:
          web:
            port: 80
            expose:
              default: true
            exposedPort: 80
            protocol: TCP
            redirectTo:
              port: websecure
              priority: 10
          websecure:
            port: 443
            expose:
              default: true
            exposedPort: 443
            protocol: TCP
            tls:
              enabled: true
              options: default
          metrics:
            port: 8080
            expose: false
            protocol: TCP
        
        persistence:
          enabled: true
          storageClass: local-path
          size: 128Mi
          path: /data
        
        rbac:
          enabled: true
        
        serviceAccount:
          enabled: true
          name: traefik
        
        # IngressClass defines this as the default ingress controller
        ingressClass:
          enabled: true
          isDefaultClass: true
        
        globalArguments:
           - "--global.checknewversion=false"
           - "--global.sendanonymoususage=false"
         
        additionalArguments:
           - "--entryPoints.websecure.http.tls.options=default"
           - "--providers.kubernetescrd=true"
           - "--providers.kubernetescrd.allowCrossNamespace=true"
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
