apiVersion: v1
kind: ConfigMap
metadata:
  name: karakeep-config
  namespace: karakeep
data:
  NEXTAUTH_URL: "https://karakeep.nihalxkumar.dev"
  OPENAI_BASE_URL: "https://generativelanguage.googleapis.com/v1beta"
  MEILI_ADDR: "http://karakeep-meilisearch:7700"
  REDIS_URL: "redis://karakeep-redis:6379"
  DATA_DIR: "/data"
  LOG_LEVEL: "info"
  # Automatic Tagging
  INFERENCE_TEXT_MODEL: "gemini-2.5-flash"
  INFERENCE_IMAGE_MODEL: "gemini-2.5-flash"
  INFERENCE_ENABLE_AUTO_TAGGING: "true"
  # Browser for crawling
  BROWSER_WEB_URL: "http://karakeep-chrome:9222"
