apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: karakeep
  namespace: karakeep

resources:
  - namespace.yaml
  - configmap.yaml
  - pvc.yaml
  - meilisearch.yaml
  - chrome.yaml
  - deployment.yaml
  - service.yaml
  - ingress-tailscale.yaml
  - middleware.yaml

generators:
  - secret-generator.yaml
