apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: tailscale-only
  namespace: karakeep
spec:
  ipAllowList:
    sourceRange:
      - 100.64.0.0/10   # Tailscale range
      - 127.0.0.1/32    # IPv4 Localhost
      - ::1/128         # IPv6 Localhost (for cloudflared)
      - 10.42.0.0/16    # Pod CIDR
      - 10.43.0.0/16    # Service CIDR
