apiVersion: ENC[AES256_GCM,data:axs=,iv:I5hOQNcViYBxfGdFfu+G4x+YXI/kJQC7HBZ/3+XwO8c=,tag:YN8hAtqBtay2/SQtgKJLUg==,type:str]
kind: ENC[AES256_GCM,data:TlxuySvg,iv:8Hlet0heLNZp2zaHkIrIF3LbUCKnb5OCqi6pcjFDh2A=,tag:Ii2TVSAEuvn9QY4KgGYixA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Qc7uRT2ihP/am2uUTfVvcA==,iv:msyEebrTpJRlYne7ExvMCwI+hURPYFGgRcdlXOVmHrY=,tag:7WVZvrAZw6z4fc9QWwvU2A==,type:str]
    namespace: ENC[AES256_GCM,data:4KfeazHDMrs=,iv:ASTVpk/90a6bbVeqaln4Vp2pchLWfu//hv/dqUhMfsg=,tag:z6Xg4pCpAZ9NhO/MVOKVzg==,type:str]
stringData:
    OPENAI_API_KEY: ENC[AES256_GCM,data:mJq6HmEhdU+CE8EdWLA6kStgJJ9m6CLG0mZt3oQTH3Iw1AQhG5vF,iv:Lg8OP4sCbDITT3IMLHkxgemTpjcdRFI6ZHW4Jna+ff0=,tag:kO16BEKQ2WXvKUIk3jI/0Q==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:kdP2q4p2DPilTWg7KhThmEtBle0BV8vokRG7QLOGxiW0PR8cRbNjz9JbevlfnTeW,iv:DMFysq/BqI2ShPilfp/JaQvSNgHkzbboW8msdlJSczs=,tag:0HEjaaQHNT7CXx5+L3YePQ==,type:str]
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:unjGtpzXbWaf5CMeDg735seTRTchpYGphwZCH5dMveQYuM99se4T7J/B0j2gZVVqhfNQpox6wGUagUayNoEr3A==,iv:gg5ItJ1sVJaW8pjRURl3QD7+odtd8qNSGAn3grSLAgY=,tag:knVhhLlNOq6KChQPfYOHMw==,type:str]
sops:
    age:
        - recipient: age1ht8d6zlqkpex3kfvr2dneldyjj7xnwh7nmjx3mmwclt7rl7upynsarwwm5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1MFMvSnVsUURsdUFWeFpw
            RndmMURaZ0RXYXVQOWlmekxsMGxsQXBRRFdNCndDeVFPS3VmVnAxNC9WZlRPZHpp
            ZDBPSmFzckpTWHNybE1VcGlFRXphM0EKLS0tIDZTVThta0dwOGNNZXpBbmhzV2JP
            MzVSYWhDbU1SNmkreWJneUVTQmp5T1kK4uq7AawtIrjVg/AqQnNnnJshoCq0zfKm
            Ad1z67gG2CeRKoVMKuwtve1cs6py/TNxhtb5o2zmQQnyJ7xguOJSpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T09:49:10Z"
    mac: ENC[AES256_GCM,data:3io11PL905XTmkeWBI1B6aIIl4zbE/bVIrCLK8OrH8dKs5MX5TcCVA7PmJfVwo6ACScgVf0yvAK9S4TF2HRQhoHzvOO/8ebhLJIleg0ygt7IUiO4sCgMhjuuhhDX9ldSWbzR9NTJbtFwwMp8PxUOMgPJNHkwKxQVKxLOlbTkVs4=,iv:824KWFL2sdc8cPr8VF5W6PciNDCHTt40pMnHTM0hOE8=,tag:R4zKeLn43MzJpE4A6aoutA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
