apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: homelab
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: "v1.16.4"
    helm:
      releaseName: cert-manager
      skipCrds: false
      values: |
        installCRDs: true
        
        resources:
          requests:
            cpu: "25m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        
        webhook:
          resources:
            requests:
              cpu: "25m"
              memory: "25Mi"
            limits:
              cpu: "100m"
              memory: "64Mi"
        
        cainjector:
          resources:
            requests:
              cpu: "25m"
              memory: "50Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
