apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: "v1.14.2"
    helm:
      releaseName: cert-manager
      skipCrds: false
  values:
    global:
      leaderElection:
        namespace: cert-manager
    
    installCRDs: true
    
    serviceAccount:
      create: true
      name: cert-manager
    
    securityContext:
      fsGroup: 1001
      runAsNonRoot: true
      runAsUser: 1001
    
    # Enable webhook
    webhook:
      enabled: true
      securePort: 10250
    
    # Global configuration
    config:
      issuers: []
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
