apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: glance
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/nihalxkumar/homelab-infra.git
    targetRevision: main
    path: kubernetes/apps/glance
  destination:
    server: https://kubernetes.default.svc
    namespace: glance
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
