apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nihalxkumar-dev
  namespace: glance
spec:
  secretName: nihalxkumar-dev-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - nihalxkumar.dev
    - "*.nihalxkumar.dev"
