apiVersion: ENC[AES256_GCM,data:dM4=,iv:PcIvgt+KOEV5XJbyxkqQf2IuGYlvmomx7D9YxUiMKpA=,tag:qVzNlrORX9cUQGOKbObQ9A==,type:str]
kind: ENC[AES256_GCM,data:+sUFJK0/,iv:hr/0fewNhpgw3lt2yzQ3nie1cOnvIZhRJJnLM8wL6Cw=,tag:/gbV86f+MV9BnA0PEGMOoQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:E731WtgtoHEh2qEMIxA=,iv:J8Yv0GwLvyU1Gnx3JJwaR37gXyBtBIaXeFhxy/r6hK0=,tag:BPCLGgVKwaKCnnIUjHUi8g==,type:str]
    namespace: ENC[AES256_GCM,data:hzXGcBBK,iv:v3rx7c7Dnv1/u8lk2qC8T6ICdhtuxy+QHO5isIEiqPE=,tag:CdI/GdTO8b2uJ/zs7bJrvA==,type:str]
type: ENC[AES256_GCM,data:CRb+cby6,iv:GGu7mWnmcox+9RUmyU5jKZbllwE1mXnlFe4qR3/SrPg=,tag:iat2/ps550qN8sxYd0+Dvg==,type:str]
stringData:
    LASTFM_API_KEY: ENC[AES256_GCM,data:5kOWsaLMv7eFDIoyzKE1uQvIpTw9FF6rdQrNnmQqzKE=,iv:uABAiXA0jQBuM6HJD5R4mhFB7A5Q+heZJIIgOUCMrMo=,tag:XLGC9+lms8Ms21ZjHHuLmA==,type:str]
sops:
    age:
        - recipient: age1ht8d6zlqkpex3kfvr2dneldyjj7xnwh7nmjx3mmwclt7rl7upynsarwwm5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoMzdjZjRMK2hrS3pSSllK
            NFJwV21mVEMyTDdkR09UeHRSejJ0ZjdlSm0wClJ5S2hUMmNtWDU4eEU5b3pLeGh1
            WG1qTXdnVWdLMFcwNXlRU1FNRjhKQ3cKLS0tIEgwNk5FOFl3cWdKekdtSktBa2Q5
            QnNLV0pveHZuV2dXbzE5d0hldE8wZ2MKDmgWjLeidESclm90eIi9xNazeNbiAcwA
            2XL0sFeA6ThJDPf202ufrWPz80CtLpADwt727TaYYotj/FAcqj/4yg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-19T18:25:07Z"
    mac: ENC[AES256_GCM,data:L7KBeb7D7RvTzv0o/xtFdo1RUpSvRRpFC94bm6j+ytB48bZQ1xg0J9ouepoai/IrUxtXZLrmExTZm4c7DuelD2AmxaRNgeeTvzSRafWPl6xcy25pZ6DifKSEuN+gDs10bS1hC+SXFbgpFF1ztHvgJd+lZClDH23qCm2kz+dNwIs=,iv:urbb38LFwXqaCsMtsuMgugG7g4YW1B1s0o+H6g9UFIA=,tag:qepLbTZeCwKMIhxOnpbO1w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
