apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: hostnetwork
spec:
  staticEndpoints:
    nodePort:
      ports:
        - port: 30000
          endPort: 32767
  statefulSet:
    pod:
      tailscaleContainer:
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 128Mi
      tailscaleInitContainer:
        resources:
          requests:
            cpu: 5m
            memory: 8Mi
          limits:
            cpu: 50m
            memory: 32Mi
