apiVersion: ENC[AES256_GCM,data:z2A=,iv:g8W9RV+RgYuwMW7ITNBdDxYvflcBkZwocNMByOttz0w=,tag:3Y3EzWDaa51Xo29o9qMxpg==,type:str]
kind: ENC[AES256_GCM,data:klABD7Sm,iv:hajgJSSzsW2+O4vofEMA0mBuAvEk7d+1VQoc8P3DRcQ=,tag:C6obWLqeQA5/6BL5nB7RBA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:rQ/YqmI+AwcNdrbn/lg=,iv:ckApfOcDpj9xCAHYqE7vrgCwBKT2ixUE7hPqNkPCXaU=,tag:pQeI238HspkMQl/M1rLrjA==,type:str]
    namespace: ENC[AES256_GCM,data:KaOcs6EVvKQU,iv:UofG/XP4Yn/q8SljsUii5PETXIejwVV+r2CDBGA1EBo=,tag:+2/iqiUklb6O1ve3KsEprg==,type:str]
stringData:
    client_id: ENC[AES256_GCM,data:d1jmMwORTLyNFNXerbvLrTU=,iv:uDgF/wMzNggAjENa+//CBa3c/yXlJUETqulr43XdVKk=,tag:XdP+nI6qcIflw+2zkZxpKA==,type:str]
    client_secret: ENC[AES256_GCM,data:5Pa8c6l3DIIyjV9ZOY2AjveTdB7RApl941yp/Vw9xcsg8yLko0vlx7Djw6zLqWEIDdFsmowlIXiXXoRLvRo8,iv:HK5Z6HRF0XiUjkG1yP/KnWLMkz1JguWj0GkkbWesKAY=,tag:Vd++XOvvqfXnGvJAg2OYWA==,type:str]
sops:
    age:
        - recipient: age1ht8d6zlqkpex3kfvr2dneldyjj7xnwh7nmjx3mmwclt7rl7upynsarwwm5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0QkV1bzZ4QW9xOHdxbElm
            a0VYeDVXZm1OeXFsbXJrRkNRZWhsS0NyVDJBCmw0Z0RHN2hRSENlSDZIbFN0Sko0
            NThqNTc2dStoSVVQYlNYQUx6bTlLckkKLS0tIHRMS1kxVVZrckRQbXBZdWtNSEZC
            MytNQzNVakM4U1RUNVE2SEtYZ0lJckEKyEY7WnLyDblSUInNYyHYWiXhcx8lB2BJ
            2hgUP1Tt0ZC2H0fnoxcgh6/dUiKhUAqBxMUt1jEJzbidwRRWdCv1hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-09T17:55:35Z"
    mac: ENC[AES256_GCM,data:F/eA8wO5GVRNAwn5ZVpeBvJU4Su9EsusUiMj4r/rev05xhFG0Uq8LcncRJMSkSYkdRGWetKQmCulnT9DjJvDtk/gCJofNKJZjOqXwa/+3PuqLzhJEwEUGOU9nFFd5cjXFs7u1gMzsiF8foc9TQPOrD77dtq5BB2Ep05nFNV2J6g=,iv:5p2UY1BUBSkgZePKK9QQpdkkHJ/M7lHcMvQvwuKnqpo=,tag:hVHo+GZnbCfgneuwCPmb4g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
