apiVersion: ENC[AES256_GCM,data:z2A=,iv:g8W9RV+RgYuwMW7ITNBdDxYvflcBkZwocNMByOttz0w=,tag:3Y3EzWDaa51Xo29o9qMxpg==,type:str]
kind: ENC[AES256_GCM,data:klABD7Sm,iv:hajgJSSzsW2+O4vofEMA0mBuAvEk7d+1VQoc8P3DRcQ=,tag:C6obWLqeQA5/6BL5nB7RBA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:rQ/YqmI+AwcNdrbn/lg=,iv:ckApfOcDpj9xCAHYqE7vrgCwBKT2ixUE7hPqNkPCXaU=,tag:pQeI238HspkMQl/M1rLrjA==,type:str]
    namespace: ENC[AES256_GCM,data:KaOcs6EVvKQU,iv:UofG/XP4Yn/q8SljsUii5PETXIejwVV+r2CDBGA1EBo=,tag:+2/iqiUklb6O1ve3KsEprg==,type:str]
stringData:
    client_id: ENC[AES256_GCM,data:myetQC/1tuvDhvwnLwGwx10=,iv:IZSPyvX9sbo5ygqhZnF1O1sGDmMsGMAtzIbYIFID8tc=,tag:lk4W0AibZwhm6NMZgyPcng==,type:str]
    client_secret: ENC[AES256_GCM,data:1LNgVujQPSCQAbSDJFMKdGdSYyi5mp+XwKACfCOnKkJIAIIhOxGhrA662e/SMSCVqs1mLx6nmoUW3Sv7Ei8cyw==,iv:aoSGwcS7IL5feqbLRYTTE+SgjKLnft0WGzqMiSTMUtk=,tag:dBsj4S4lMM0zHfclzLdohg==,type:str]
sops:
    age:
        - recipient: age1ht8d6zlqkpex3kfvr2dneldyjj7xnwh7nmjx3mmwclt7rl7upynsarwwm5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0QkV1bzZ4QW9xOHdxbElm
            a0VYeDVXZm1OeXFsbXJrRkNRZWhsS0NyVDJBCmw0Z0RHN2hRSENlSDZIbFN0Sko0
            NThqNTc2dStoSVVQYlNYQUx6bTlLckkKLS0tIHRMS1kxVVZrckRQbXBZdWtNSEZC
            MytNQzNVakM4U1RUNVE2SEtYZ0lJckEKyEY7WnLyDblSUInNYyHYWiXhcx8lB2BJ
            2hgUP1Tt0ZC2H0fnoxcgh6/dUiKhUAqBxMUt1jEJzbidwRRWdCv1hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-11T09:45:55Z"
    mac: ENC[AES256_GCM,data:JayEwySZ9s/Ty3O9U2fNKtVJgKoCi2olqBeU6DFoO2unDMSEivWYzX2AdEmuGHwLmkC7Pjy68/HIiM/SmUL1BhWM1cmZwaBUhMEAOdiFwsi9E0ik2nU/TzK0a6CFxiP9bvUQj8WkDysHAymhQqQWWeZCR2kYe5PHaYw/9sU/sd0=,iv:RLdNv/cQi/EgLn+6T/5enLCUSAW/H5rB65GGAhDYV5I=,tag:fo9BywA9TbCPrs3h0N/2rA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
