apiVersion: ENC[AES256_GCM,data:z2A=,iv:g8W9RV+RgYuwMW7ITNBdDxYvflcBkZwocNMByOttz0w=,tag:3Y3EzWDaa51Xo29o9qMxpg==,type:str]
kind: ENC[AES256_GCM,data:klABD7Sm,iv:hajgJSSzsW2+O4vofEMA0mBuAvEk7d+1VQoc8P3DRcQ=,tag:C6obWLqeQA5/6BL5nB7RBA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:rQ/YqmI+AwcNdrbn/lg=,iv:ckApfOcDpj9xCAHYqE7vrgCwBKT2ixUE7hPqNkPCXaU=,tag:pQeI238HspkMQl/M1rLrjA==,type:str]
    namespace: ENC[AES256_GCM,data:KaOcs6EVvKQU,iv:UofG/XP4Yn/q8SljsUii5PETXIejwVV+r2CDBGA1EBo=,tag:+2/iqiUklb6O1ve3KsEprg==,type:str]
stringData:
    client_id: ENC[AES256_GCM,data:p0Y6smN6p4TV3gUkDKaP9gk=,iv:Q4zwVLflywbdsCgk/RzJ1nn2a/A+iapByGyuLtW38I4=,tag:fvIDFWHjGt2g72x6EpZc6A==,type:str]
    client_secret: ENC[AES256_GCM,data:o2qzDH+gL3SMYCzfkdGbvw2Y/VlHyIevIg7T+Kfa9bBnGf5tC10eyGR/nFI3dLa2buJvKC6GNU3uOIIwMxMu,iv:8h9VKY9MqZsZdnxrxFw1JP4vWgGFZzA1Gd1W2X34Fk0=,tag:S1ZS7c+MLyJOK/4JbFHvcA==,type:str]
sops:
    age:
        - recipient: age1ht8d6zlqkpex3kfvr2dneldyjj7xnwh7nmjx3mmwclt7rl7upynsarwwm5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0QkV1bzZ4QW9xOHdxbElm
            a0VYeDVXZm1OeXFsbXJrRkNRZWhsS0NyVDJBCmw0Z0RHN2hRSENlSDZIbFN0Sko0
            NThqNTc2dStoSVVQYlNYQUx6bTlLckkKLS0tIHRMS1kxVVZrckRQbXBZdWtNSEZC
            MytNQzNVakM4U1RUNVE2SEtYZ0lJckEKyEY7WnLyDblSUInNYyHYWiXhcx8lB2BJ
            2hgUP1Tt0ZC2H0fnoxcgh6/dUiKhUAqBxMUt1jEJzbidwRRWdCv1hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-11T11:33:26Z"
    mac: ENC[AES256_GCM,data:X4zzS0+ZgFD0v2OA5PSnxMvCf9t4CKMsebeCpnyht9rGIbfc2oZhcdLyLHWbf2XhpP0HJKM11k6dQcJ8+0sXFSPBXXnGXEqlv3VKd7hlSEvBkEuW5r7br9iu2Tcb8cmGyWcflpcr1csu8Ste9VhyaJfU38+4dWb5B3hKEQgVWYY=,iv:TdVQxp9/eGY4bnOrosDRnX3x1uvS2/JLJj5Iuq8p3jk=,tag:KUggTV8HR5KBrBb4qzgEGA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
