---
apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-config
  namespace: n8n
  labels:
    app: n8n
data:
  GENERIC_TIMEZONE: "America/New_York"
  TZ: "America/New_York"
  
  N8N_HOST: "n8n.nihalxkumar.dev"
  N8N_PORT: "5678"
  N8N_PROTOCOL: "https"
  WEBHOOK_URL: "https://n8n.nihalxkumar.dev"
  N8N_EDITOR_BASE_URL: "https://n8n.nihalxkumar.dev"
  
  EXECUTIONS_MODE: "regular"
  EXECUTIONS_PROCESS: "main"
  EXECUTIONS_DATA_SAVE_ON_ERROR: "all"
  EXECUTIONS_DATA_SAVE_ON_SUCCESS: "all"
  EXECUTIONS_DATA_SAVE_ON_PROGRESS: "true"
  EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS: "true"
  
  WORKFLOWS_DEFAULT_NAME: "My Workflow"
  
  N8N_SECURE_COOKIE: "true"
  N8N_SKIP_WEBHOOK_DEREGISTRATION_SHUTDOWN: "true"
  
  N8N_LOG_LEVEL: "debug"
  N8N_LOG_OUTPUT: "console"
  N8N_PAYLOAD_SIZE_MAX: "16"
  
  N8N_DIAGNOSTICS_ENABLED: "true"
  N8N_METRICS: "true"
  N8N_USER_MANAGEMENT_DISABLED: "false"
  
  DB_TYPE: "sqlite"
