apiVersion: ENC[AES256_GCM,data:Gh8=,iv:LCyvxcucF7RSplO/HqtICkNoA9B9d3yfC4PfBwp4NJE=,tag:eujnyXRp2vYUrtEAK6zxTw==,type:str]
kind: ENC[AES256_GCM,data:fTV8wmyb,iv:4qXLh2c9WyQBZrM1wbbRrGdtqdO20/MvHlW2j2TT1i4=,tag:PNf0ErdQmCTBe9JU1UfWSw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:i6PJx3PO+mj3Ug==,iv:5Le9ZUNPYRoIxoAQHgZoUSE5Czc7X+uPLbPTVsAWNfM=,tag:LOotR2GQ9Ji/wN07zDw6qg==,type:str]
    namespace: ENC[AES256_GCM,data:m72e,iv:ASlxEeP9wN2INR5RRrMAaKXIK2tePRxK/j/aWnP+Kpc=,tag:p3eHMg8uhjrF0ByrNBbeOA==,type:str]
    labels:
        app: ENC[AES256_GCM,data:g+da,iv:yCUD8uyqEL6brf0Ir8GAWtXpogeO7giTMZcKt/tASTg=,tag:QfNfpcSjUjXNHa8S+a1Q8Q==,type:str]
type: ENC[AES256_GCM,data:cK11sSLb,iv:QtWCv23uVUxP0/+PPGJHHFbCxXTcaK6qfiR++Zjfk1M=,tag:74QpZDZ/LysBCRQue6UleQ==,type:str]
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:+Ud8+CFatuwBrSnaITWboOk36w0FhHmliryVU3RX0FUNMv6Y414sADojuRA=,iv:cZqZIa1z96kLQqKdedn04sVSkRxYKgFcVgX97yiGH7A=,tag:AVr5rldD0KB8TXaHAyLeIQ==,type:str]
    N8N_BASIC_AUTH_USER: ENC[AES256_GCM,data:OafM3yQ=,iv:cifyw3IeO0bSWpyy4gAnAgG9sXrb2PnmiaqtkUugaM8=,tag:htC7QacfKyvPnhcKzozirQ==,type:str]
    N8N_BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:12cTxMwMz4y3MkVebkkCSmbS,iv:myM6l+OnN6M5MDNbRcp4FN5DHGrGViMn+oywMQ3zCq8=,tag:mzijAkXYhqpKLcvnNLM5sg==,type:str]
sops:
    age:
        - recipient: age1ht8d6zlqkpex3kfvr2dneldyjj7xnwh7nmjx3mmwclt7rl7upynsarwwm5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcGtJaGlBWUtqQkxXVDk0
            aG1tKy9FSEF0QUVJZEl0MEFaMHczYmhRcGlVCnFyU1EvV0JRUzdFa01YaE9PcGxY
            blZRRFdrc0hxZkZWYTE4cndSR3JCbjAKLS0tIFc2M3VwMnRqTFZCOEd4aDhyOEZu
            RUFTSGdNN1BIczJDcEdSbE5YYldZMU0Kf/a5S3oGaUViQAWOfKfIIuTR5DILJ+bg
            q/cNiAwFW/SIxfrLbcjCNUCh+jiND5WSeR2cEDlZf+Cdo0EZofbT2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-23T16:46:38Z"
    mac: ENC[AES256_GCM,data:JZLne+4wYlhkK1T9qG4Dwx0t686huptDSE7XB8tdh1UDR7MldfrySSSdlKx6HUIq9VV3NGyX7Q2W3wptlE3AMeANew5gpTTer0KxdChsTQSn63cmqF/ixeB1fdLrU35X7FnmhMe1HxEfIuZFkJBrf+b/1eerunckEhC0iy7BjAc=,iv:zjxRcuu2R1bpU884M8TejYKtuEtZCcRMvNHTTqrjKv8=,tag:mzk0FLMRCnMlZwgi6Kj05Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
